services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - homeserver

networks:
  homeserver:
    external: true
